version: '3.5'
services:

  jellymal:
    image: jellymal:latest
    container_name: jellymal
    user: 1000:1000
    environment:
     - JELLYFIN_HOST=${JELLYFIN_HOST}
     - JELLYFIN_TOKEN=${JELLYFIN_TOKEN}
     - JELLYFIN_USER=${JELLYFIN_USER}
     - MAL_CLIENT_ID=${MAL_CLIENT_ID}
     - MAL_CLIENT_SECRET=${MAL_CLIENT_SECRET}
     - MAL_API_REDIRECT_URL=${MAL_API_REDIRECT_URL}

    volumes:
     - ${YOUR_VOLUME}/data:/data
